server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: member-management
          uri: http://localhost:8082
          predicates:
            - Path=/customers/**, 
        - id: product-management
          uri: http://localhost:8083
          predicates:
            - Path=/products/**, 
        - id: order-processing
          uri: http://localhost:8084
          predicates:
            - Path=/orders/**, 
        - id: supplier-management
          uri: http://localhost:8085
          predicates:
            - Path=/suppliers/**, 
        - id: delivery-service
          uri: http://localhost:8086
          predicates:
            - Path=/deliveries/**, 
        - id: coupon
          uri: http://localhost:8087
          predicates:
            - Path=/coupons/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: member-management
          uri: http://memberManagement:8080
          predicates:
            - Path=/customers/**, 
        - id: product-management
          uri: http://productManagement:8080
          predicates:
            - Path=/products/**, 
        - id: order-processing
          uri: http://orderProcessing:8080
          predicates:
            - Path=/orders/**, 
        - id: supplier-management
          uri: http://supplierManagement:8080
          predicates:
            - Path=/suppliers/**, 
        - id: delivery-service
          uri: http://deliveryService:8080
          predicates:
            - Path=/deliveries/**, 
        - id: coupon
          uri: http://coupon:8080
          predicates:
            - Path=/coupons/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
